on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      -
        uses: googleapis/release-please-action@v4
        id: release
        with:
          # this assumes that you have created a personal access token
          # (PAT) and configured it as a GitHub action secret named
          # `MY_RELEASE_PLEASE_TOKEN` (this secret name is not important).
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          # optional. customize path to release-please-config.json
          config-file: release-please-config.json
          # optional. customize path to .release-please-manifest.json
          manifest-file: .release-please-manifest.json

      -
        uses: actions/checkout@v4
        if: ${{ steps.release.outputs.pr }}
        with:
          ref: ${{ fromJson(steps.release.outputs.pr).headBranchName }}

      -
        uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.pr }}
        with:
          node-version: 22

      -
        run: npm ci
        if: ${{ steps.release.outputs.pr }}


      -
        name: Run CHANGELOG.md through markdownlint-cli2
        if: ${{ steps.release.outputs.pr }}
        run: npx markdownlint-cli2 CHANGELOG.md --fix

      -
        name: Commit and push
        if: ${{ steps.release.outputs.pr }}
        uses: EndBug/add-and-commit@v9
        with:
          add: 'CHANGELOG.md'
          message: 'chore: run CHANGELOG.md through markdownlint-cli2'
          default_author: user_info